### PR TITLE
Submission of test cases

### LINKED ISSUE #63: Submission of test cases (Gherkin feature files)
Hi all,

As briefly discussed during the SimSwap meeting on 19/10/23 - I have a number of Gherkin test cases that I'm interested in submitting. Examples are below. Please can you take a look and advise if I should create a Pull Request? 

The Commonalities [API Readiness Checklist](https://github.com/camaraproject/WorkingGroups/blob/7baa0dd1faf4276344ba62a334f52eb06bedd751/Commonalities/documentation/API-Readiness-Checklist.md) does not yet have a reference template for test cases (it is labelled as TBD) - however I have looked through other CAMARA repositories and noted Gherkin feature files from the following projects (click to be taken to the feature files):

* [EdgeCloud (Traffic Influence)](https://github.com/camaraproject/EdgeCloud/blob/main/code/Test_definitions/Traffic_Influence_Test.feature)
* [QualityOnDemand](https://github.com/camaraproject/QualityOnDemand/blob/main/code/cucumber/src/test/resources/feature/QoD_API_Test.feature)
* [HomeDevicesQoD](https://github.com/camaraproject/HomeDevicesQoD/blob/main/code/Test_definitions/home_devices_qod_setQos.feature)

The SimSwap test cases would follow a similar pattern to the above feature files. These are some examples:
```Gherkin

Feature: Check if SIM Swap has been performed during a past period 

  @Test_Verify_Swap_True
  Scenario: Confirm that a SIM has been swapped
    Given a valid phone number "<phoneNumber>" whose SIM has been swapped in the last "<maxAge>" hours
    When a Check SimSwap request is made with a maxAge parameter of "<maxAge>"
    Then the response status code should be 200
    And the response body should confirm that a SIM swap has been performed 

    Examples:
      | phoneNumber   | maxAge |
      | +346661113334 | 24     |
      | +447748357814 | 48     |      

  @Test_Verify_Swap_True_Default_MaxAge
  Scenario: Confirm that a SIM has been swapped without specifying maxAge (should default to maxAge of 240)
    Given a valid phone number "<phoneNumber>" whose SIM has been swapped within the default max age value (240)
    When a Check SimSwap request is made without a maxAge parameter
    Then the response status code should be 200
    And the response body should confirm that a SIM swap has been performed 

  @Test_Verify_Swap_False
  Scenario: Confirm that a SIM has not been swapped
    Given a valid phone number "<phoneNumber>" whose SIM has been swapped in the last "<maxAge>" hours
    When a Check SimSwap request is made with a maxAge parameter of "<maxAge>" 
    Then the response status code should be 200
    And the response body should confirm that a SIM swap has not been performed 

    Examples:
      | phoneNumber   | maxAge |
      | +346661113334 | 24     |
      | +447748357814 | 48     |       

  @Test_Negative_MaxAge
  Scenario: Input an invalid maxAge value (less than 1)
    Given a valid phone number "<phoneNumber>" whose SIM has been swapped in the last "<maxAge>" hours
    When a Check SimSwap request is made with a maxAge parameter of "-1"
    Then the response status code should be 400
    And the response should contain an error message indicating an invalid argument
```

I have further test cases but have included the above as an example of the language and syntax. Appreciate your thoughts.

### PR DESCRIPTION
**Pull request by trehman-gsma**
#### What type of PR is this?

Tests

#### What this PR does / why we need it:

Initial test case proposal. The [API readiness checklist](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/API-Readiness-Checklist.md) states that API test cases should be created. 

Created two `.feature` files that contain Gherkin test cases. One file containing test cases for `POST /retrieve-date` and the second file containing test cases for `POST /check`.

The files were created under the `/code/Test_definitions` as per guidance in https://github.com/camaraproject/Template_Lead_Repository/pull/1

#### Which issue(s) this PR fixes:

Fixes #63 

#### Special notes for reviewers:

Initial test case proposal. Will amend as per feedback. 

#### Changelog input

```
Created /code/Test_definitions/check_simswap.feature containing test cases for POST /check

Created /code/Test_definitions/retrieve_simswap_date.feature containing test cases for POST /retrieve-date

```

### CODE REVIEW

**Comment by fernandopradocabrillo** [comment]
Hi @trehman-gsma! 
Thank you for the proposal and starting the discussion regarding the test scenarios.
I've been reviewing it and from Telefónica we have a proposal too that is align with the existing one in Home Devices Qod, which is the only API that has an ATP at the moment. It is a little bit more complete and detailed I believe. 

I wasn't sure how to include our proposal so I created a different PR #70 

Any feedback is welcome 😄

**Comment by bigludo7** [comment]
Hello @trehman-gsma 
Thanks !
I have same comment that for PR#70 
What about one additional test for the check when the msisdn obtained from the network in the authorization first step (and passed in the token) is distinct from the one we get in the POST payload ?
We have added 403 for this error.

**Comment by trehman-gsma** [comment]
Hi @fernandopradocabrillo @bigludo7,

Sorry I didn't see this earlier (notifications landed in an unmonitored email folder - my bad).

I'm happy to adopt PR #70 instead of this PR. It covers most of the same test cases - the language differs but that's a syntactic matter to be agreed) - and I can see there has been more detailed discussion within the PR.

Will provide feedback in PR #70.

Shall I close this PR or wait for camaraproject/Commonalities#94 to close?

**Comment by bigludo7** [comment]
@trehman-gsma You should keep it open and waiting for https://github.com/camaraproject/Commonalities/issues/94 outcome. Both your and @fernandopradocabrillo  contributions are valuable. We need to agreed on a common pattern and once done we will work from the closest one.

**Comment by bigludo7** [comment]
Hi @trehman-gsma 
Could you please take a look on what @fernandopradocabrillo proposed it [here](https://github.com/camaraproject/SimSwap/pull/70) as it is now aligned with CAMARA test definition guideline.

We can probably close this PR and work only on the PR70 - what do you think?

**Comment by trehman-gsma** [comment]
Closing this PR in favour of #70 (aligned with CAMARA test definition guidelines)

**Pull request closed without merging**
