### PR TITLE
Update and review of maintainers.md file

### LINKED ISSUE #105: Update and review of MAINTAINERS.MD file
**Problem description**

To execute https://github.com/camaraproject/Governance/issues/134 we need the GitHub Usernames of all Maintainers in MAINTAINERS.MD. For that purpose a new column will be added.

In addition the TSC requested to use this opportunity to review all Maintainer files if they are still current (e.g. the Maintainer still active, with the listed affiliation, etc). 

**Expected action**

Please review the PR which will be created for this issue. Please check if all listed people are still committed, active Maintainers according to the role description. Propose needed changes. 

And: Add missing GitHub Usernames.

**Additional context**

The PR will also add the following lines at the end of CODEOWNER file to ensure that CAMARA Admins are involved in all changes of the both files:

```
# Owners of the CODEOWNER and Maintainer.md files are the admins of CAMARA (to allow them to keep the teams within the CAMARA organization in sync in case of changes)
/CODEOWNERS @camaraproject/admins
/MAINTAINERS.MD @camaraproject/admins
```

### PR DESCRIPTION
**Pull request by hdamker**
#### What type of PR is this?

* subproject management

#### What this PR does / why we need it:

See 
* #105 

#### Which issue(s) this PR fixes:

Fixes #105

#### Special notes for reviewers:

In case Jung Sun-sun is an active Maintainer of this Sub Project:
* suggest the GitHub Username of Jung Sun-sun
~~* ensure that they is subscribed to the Sub Project mailing list (and first CAMARA all)~~

### CODE REVIEW

**Review by bigludo7 — DISMISSED** [review]
Good for me. Thanks.
@hdamker how I can check th Sub Project mailing list? 
I'm on the page https://lists.camaraproject.org/g/sp-ssw but only able to see 52 participants but not the listing.

**Review by fernandopradocabrillo — DISMISSED** [review]
LGTM

**Comment by hdamker** [comment]
@bigludo7 @fernandopradocabrillo thanks for the approvals, but what about Jung Yun-sun (Serena)? If you want to keep the line please suggest the GitHub Username.

**Comment by bigludo7** [comment]
> @bigludo7 @fernandopradocabrillo thanks for the approvals, but what about Jung Yun-sun (Serena)? If you want to keep the line please suggest the GitHub Username.

Not sure how we can proceed. I checked Jung Yun-sun (Serena) was not active on CAMARA SIM Swap since early 2023.
Do you have, you or Markus, a contact at SK Telecom related to CAMARA ?

**Comment by hdamker** [comment]
> Not sure how we can proceed. I checked Jung Yun-sun (Serena) was not active on CAMARA SIM Swap since early 2023.
> Do you have, you or Markus, a contact at SK Telecom related to CAMARA ?

I would propose to follow for now the [ProjectStructureAndRoles.md](https://github.com/camaraproject/Governance/blob/main/ProjectStructureAndRoles.md): "A Maintainer with no Project activity for a year is considered to have resigned."

**Review by bigludo7 — COMMENTED** [review]
Agreed with your proposal @hdamker 
Happy to reinsert Jung Yun-sun in future.

**Comment by hdamker** [comment]
Thanks @bigludo7. I now need again a Codeowner approval. Or do you want to involve Toshi and Jose into the review first?

**Comment by fernandopradocabrillo** [comment]
> Agreed with your proposal @hdamker Happy to reinsert Jung Yun-sun in future.

Also agree, and +1 to reinsert Jung if becomes active again.

From our side there is no need to involve Jose

**Review by bigludo7 — APPROVED** [review]

**Comment by bigludo7** [comment]
I think we can merge this one ;)

**Review by fernandopradocabrillo — APPROVED** [review]
LGTM

**Pull request merged**
