### PR TITLE
Add EventSimSwap to Sim Swap Subscriptions

### LINKED ISSUE #156: [Sim-Swap-Subscription]: EventSimSwap is missing
**Problem description**
Hi all,
the event for a sim swap is missing in the API specification.

**Expected behavior**
API specification should include:

```
EventSimSwap:
      description: event structure for event sim swapped
      allOf:
        - $ref: "#/components/schemas/CloudEvent"
        - type: object    
          properties:
             data:
                $ref: "#/components/schemas/Swapped" 
```

### PR DESCRIPTION
**Pull request by daniel-dierich**
#### What type of PR is this?

Add one of the following kinds:

* correction

#### What this PR does / why we need it:

Adds the event for a sim swap to the API specification for sim-swap-subscriptions. 

#### Which issue(s) this PR fixes:

Fixes #156

### CODE REVIEW

**Comment by bigludo7** [comment]
@daniel-dierich Thanks - Yes we should fix this !

Are you able to manage EasyCLA with your company to LF?
If not let me know and I can craft the PR to fix this.

Thanks a lot for the contribution.

**Review by bigludo7 — DISMISSED** [review]
LGTM

**Comment by bigludo7** [comment]
@daniel-dierich if you have issue/question related to easyCLA --> @wrathwolf can help.

**Comment by daniel-dierich** [comment]
I have been added to the easyCLA of my company but I seem unable to restart the check.

**Comment by bigludo7** [comment]
> I have been added to the easyCLA of my company but I seem unable to restart the check.

Perhaps it requires some time?
I'v send a check - only megalinter is checked.
BTW you have a trailing space un line 680 making megalinter unhappy.

**Review by bigludo7 — APPROVED** [review]
LGTM

**Comment by fernandopradocabrillo** [comment]
@daniel-dierich Thanks for the PR!

please could you also change the API version to `wip` and the url server version to `vwip`?

**Review by fernandopradocabrillo — APPROVED** [review]
Thanks!

**Review by bigludo7 — APPROVED** [review]
LGTM

**Pull request merged**
