### PR TITLE
glossary alignment

### PR DESCRIPTION
**Pull request by monamok**
#### What type of PR is this?

* fix

#### What this PR does / why we need it:

The parameters naming alignment with [Glossary](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Glossary.md) 

#### Which issue(s) this PR fixes:

Fixes (https://github.com/camaraproject/SimSwap/issues/41)

#### Special notes for reviewers:

- The parameters names were indicated in [Glossary](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Glossary.md) in order to be unified in the whole CAMARA project. This PR is to change msisdn to phoneNumber. 
- Also the example of phoneNumber was change to make it more clear that country code must be included.
- Some typo fixes and minor changes were included

#### Changelog input

Changelogs will be included once https://github.com/camaraproject/SimSwap/pull/28 in accepted and merged

### CODE REVIEW

**Comment by monamok** [comment]
> We will introduce the UTC precision later?

We can include it in the PR we have to open for https://github.com/camaraproject/SimSwap/issues/42

**Comment by monamok** [comment]
> Added UTC precision

@bigludo7 are we going to wait for the commonalities issue about this to get resolved or are we going to merge this PR and then align it with the decision afterwards?

**Comment by bigludo7** [comment]
@monamok I suggest to wait tomorrow Commonalities call. 
If the team there pick an option during the call we can accommodate our api accordingly.
If no decision, we remove the UTC precision from our API and we merge without it.

Probably good to inform @DT-DawidWroblewski. I should not be able to connect tomorrow  to the Commonalities call so hope someone can trigger the discussion (Dawid, you or @gregory1g )
Work for you?

**Comment by monamok** [comment]
@bigludo7 I removed UTC for the moment so if you approve and @DT-DawidWroblewski agrees too, we can merge and close this PR tomorrow during the bi-weekly meeting.
For the other two issues I will open a new PR afterwards.

**Review by bigludo7 — DISMISSED** [review]
OK work for me as well.
We can create another PR for UTC after.
Let's go for this

**Comment by monamok** [comment]
@bigludo7 thank you.

**Review by DT-DawidWroblewski — APPROVED** [review]
all good

**Pull request merged**
