### PR TITLE
Contact and TermsOfService fields should be removed from info object 

### LINKED ISSUE #141: Contact and TermsOfService fields should be removed from info object
**Problem description**
`Contact` and `TermsOfService` fields in Camara specifications do not include valuable information.
It was decided to remove them as optional fields from `info` object:
https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#info-object

**Expected behavior**
Remove the optional fields from both OAS files.

**Additional context**
Fields may be added by API Providers documenting their APIs.
https://github.com/camaraproject/Commonalities/pull/214

### PR DESCRIPTION
**Pull request by bigludo7**
#### What type of PR is this?

Add one of the following kinds:

* correction

#### What this PR does / why we need it:

Removed Contact and TermsOfService fields from info object 

#### Which issue(s) this PR fixes:

Fixes #141 

#### Special notes for reviewers:

version back to `wip`

#### Changelog input

```
 release-note
-Removed Contact and TermsOfService fields from info object 

```

#### Additional documentation 

This section can be blank.

```
docs

```

### CODE REVIEW

**Comment by rartych** [comment]
I guess, the same fix is needed in sim-swap-subscriptions.yaml

**Comment by bigludo7** [comment]
Hopefully you're on duty @rartych  :)
Thanks !!!!

**Comment by hdamker** [comment]
If you don't plan to release sim-swap-subscriptions.yaml here anymore, you don't need to touch it. It wouldn't harm either as you will delete the wip version before the release. 

For the transfer to another repository I would only pick a released version to have a change history without a gap (I guess we need to describe this process).

**Review by fernandopradocabrillo — APPROVED** [review]
LGTM

**Review by hdamker — APPROVED** [review]

**Pull request merged**
